spring:
  application:
    name: TICKET-SERVICE
  h2:
    console:
      settings:
        trace: true
  jpa:
    show-sql: true

server:
  port: 6060

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true